# Generated by Django 3.0.6 on 2020-05-26 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200526_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='Priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.Priority'),
        ),
    ]
