# Generated by Django 3.0.6 on 2020-05-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20200526_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='Priority',
            new_name='label',
        ),
        migrations.AddField(
            model_name='todo',
            name='DueDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
