# Generated by Django 3.0.6 on 2020-05-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20200529_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='Is_Archeived',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
