# Generated by Django 3.0.6 on 2020-05-29 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_todo_is_archeived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='label',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todo.Priority'),
            preserve_default=False,
        ),
    ]
